{
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "4.3/CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                    "version": "3.0"
                }
            ],
            [
                {
                    "vectorString": "3.5/AV:N/AC:M/Au:S/C:N/I:N/A:P",
                    "version": "2.0"
                }
            ]
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "openshift before versions 3.3.1.11, 3.2.1.23, 3.4 is vulnerable to a flaw when a volume fails to detach, which causes the delete operation to fail with 'VolumeInUse' error. Since the delete operation is retried every 30 seconds for each volume, this could lead to a denial of service attack as the number of API requests being sent to the cloud-provider exceeds the API's rate-limit."
            }
        ]
    },
    "data_type": "CVE",
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "openshift 3.3.1.11"
                                        },
                                        {
                                            "version_value": " openshift 3.2.1.23"
                                        },
                                        {
                                            "version_value": " openshift 3.4"
                                        }
                                    ]
                                },
                                "product_name": "openshift"
                            }
                        ]
                    },
                    "vendor_name": ""
                }
            ]
        }
    },
    "data_format": "MITRE",
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-460"
                    }
                ]
            }
        ]
    },
    "data_version": "4.0",
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-9592"
            }
        ]
    },
    "CVE_data_meta": {
        "ID": "CVE-2016-9592",
        "ASSIGNER": "lpardo@redhat.com"
    }
}
