{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2010-3493",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "http://www.openwall.com/lists/oss-security/2010/09/09/6"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2010/09/11/2"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2010/09/22/3"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2010/09/24/3"
         },
         {
            "url" : "http://bugs.python.org/issue6706"
         },
         {
            "url" : "https://bugs.launchpad.net/zodb/+bug/135108"
         },
         {
            "url" : "http://bugs.python.org/issue9129"
         },
         {
            "url" : "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289"
         },
         {
            "url" : "http://svn.python.org/view?view=rev&revision=84289"
         },
         {
            "url" : "https://bugzilla.redhat.com/show_bug.cgi?id=632200"
         },
         {
            "url" : "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216"
         },
         {
            "url" : "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215"
         },
         {
            "url" : "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html"
         },
         {
            "url" : "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1596-1"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1613-2"
         },
         {
            "url" : "http://www.ubuntu.com/usn/USN-1613-1"
         },
         {
            "url" : "http://www.securityfocus.com/bid/44533"
         },
         {
            "url" : "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210"
         },
         {
            "url" : "http://secunia.com/advisories/43068"
         },
         {
            "url" : "http://secunia.com/advisories/50858"
         },
         {
            "url" : "http://secunia.com/advisories/51024"
         },
         {
            "url" : "http://secunia.com/advisories/51040"
         },
         {
            "url" : "http://www.vupen.com/english/advisories/2011/0212"
         }
      ]
   }
}
