{
   "CVE_data_meta" : {
      "ASSIGNER" : "cve@mitre.org",
      "ID" : "CVE-2013-1664",
      "STATE" : "PUBLIC"
   },
   "affects" : {
      "vendor" : {
         "vendor_data" : [
            {
               "product" : {
                  "product_data" : [
                     {
                        "product_name" : "n/a",
                        "version" : {
                           "version_data" : [
                              {
                                 "version_value" : "n/a"
                              }
                           ]
                        }
                     }
                  ]
               },
               "vendor_name" : "n/a"
            }
         ]
      }
   },
   "data_format" : "MITRE",
   "data_type" : "CVE",
   "data_version" : "4.0",
   "description" : {
      "description_data" : [
         {
            "lang" : "eng",
            "value" : "The XML libraries for Python 3.4, 3.3, 3.2, 3.1, 2.7, and 2.6, as used in OpenStack Keystone Essex, Folsom, and Grizzly; Compute (Nova) Essex and Folsom; Cinder Folsom; Django; and possibly other products allow remote attackers to cause a denial of service (resource consumption and crash) via an XML Entity Expansion (XEE) attack."
         }
      ]
   },
   "problemtype" : {
      "problemtype_data" : [
         {
            "description" : [
               {
                  "lang" : "eng",
                  "value" : "n/a"
               }
            ]
         }
      ]
   },
   "references" : {
      "reference_data" : [
         {
            "url" : "http://lists.openstack.org/pipermail/openstack-announce/2013-February/000078.html"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2013/02/19/2"
         },
         {
            "url" : "http://www.openwall.com/lists/oss-security/2013/02/19/4"
         },
         {
            "url" : "http://blog.python.org/2013/02/announcing-defusedxml-fixes-for-xml.html"
         },
         {
            "url" : "http://bugs.python.org/issue17239"
         },
         {
            "url" : "https://bugs.launchpad.net/nova/+bug/1100282"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2013-0658.html"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2013-0657.html"
         },
         {
            "url" : "http://rhn.redhat.com/errata/RHSA-2013-0670.html"
         },
         {
            "url" : "http://ubuntu.com/usn/usn-1757-1"
         }
      ]
   }
}
